name: face_graph_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  bdaya_custom_splash:
    git:
      url: https://github.com/Bdaya-Dev/custom-splash.git
      ref: master
  bdaya_repository_pattern:
    git:
      url: git@github.com:AbdrahumanFikry/Flutter-Repository-Pattern.git
      ref: master
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  get: 4.6.1
  intl: ^0.17.0
  file_picker: ^3.0.2+2
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.0.0+2
  uuid: ^3.0.5


dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.1

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/